---
title: "sta206hw4"
author: "RanLiu"
date: "October 24, 2015"
output: word_document
---
(a). 
```{r, fig.width = 15, fig.height = 10}
setwd("E:/RLiu_R/sta206")
property = read.table("property.txt")
colnames(property) = c("rentalRate", "age", "operating", "vacancy", "sqfootage")
plot(property, main = "Scatter Plot Matrix of Estate Data")
(correlationMatrix = round(cor(property), 2))
```

(b).
```{r}
model1 = lm(rentalRate ~ age + operating + vacancy + sqfootage, data = property)
round(model1$coefficients, 2)
summary(model1)
mse = 1.137^2
```

(c).
```{r, fig.width = 15, fig.height = 10}
par(mfrow = c(1, 3))
plot(model1, which = 1)
plot(model1, which = 2)
boxplot(model1$residuals, main = "boxplot of residuals", ylab = "residuals value", xlab = "residuals")
```

(d).
```{r, fig.width = 15, fig.height = 10}
par(mfrow = c(2, 2))
#lapply(colnames(property)[-1], function(x) plot(property$x, model1$residuals))
plot(property$age, model1$residuals)
plot(property$operating, model1$residuals)
plot(property$vacancy, model1$residuals)
plot(property$sqfootage, model1$residuals)
#interaction terms
par(mfrow = c(2, 3))
with(property, plot(age*operating, model1$residuals))
with(property, plot(age*vacancy, model1$residuals))
with(property, plot(age*sqfootage, model1$residuals))
with(property, plot(operating*vacancy, model1$residuals))
with(property, plot(operating*sqfootage, model1$residuals))
with(property, plot(vacancy*sqfootage, model1$residuals))
```

(e)
```{r}
summary(model1)
```

(f)
```{r}
anova(model1)
```

(g)
```{r}
model2 = lm(rentalRate ~ age + operating + sqfootage, data = property)
round(model2$coefficients, 2)
summary(model2)
```

(h)
```{r}
anova(model2)
coeffInt = confint(model2, parm = c("age", "operating", "sqfootage"), level = 0.95)
(coeffInt = round(coeffInt, 4))
coeffInt = confint(model1, parm = c("age", "operating", "sqfootage"), level = 0.95)
(coeffInt = round(coeffInt, 4))
```

(i)
```{r}
newppt = data.frame(age = 4, operating = 10, vacancy = 0.1, sqfootage = 80000)
predict(model1, newppt, interval = "prediction", se.fit = TRUE)
predict(model2, newppt, interval = "prediction", se.fit = TRUE)
```


